### ISSUE TITLE
Since updating to 1.3 VS2013 crashes on building

### ISSUE THREAD

**Issue by MartinL0815** [nagits/BuildVision#1]
Hi,

what can I do to support you fixing the crash?

Currently I disabled BuildVision, so I could enable it again and try to "debug" VS2013 after its crash starting to build?

Best regards,

Martin

**Comment by nagits** [comment]
Hi Martin,

I think I've found the reason.
To confirm my assumption, please check whether you have the following error in the Windows Event Log (Win+R, ```eventvwr /c:Application```):
* Source: .NET Runtime
* EventID: 1026
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Windows.Media.Animation.Storyboard.VerifyPathIsAnimatable(System.Windows.PropertyPath)
   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(System.Windows.Media.Animation.Clock, 
..................
```

**Comment by MartinL0815** [comment]
Here the events from a just forced crash of VS2013 by enabling BuildVision and starting a build:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Events>
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
      <Provider Name="Application Error"/>
      <EventID Qualifiers="0">1000</EventID>
      <Level>2</Level>
      <Task>100</Task>
      <Keywords>0x80000000000000</Keywords>
      <TimeCreated SystemTime="2015-03-30T16:49:51.000000000Z"/>
      <EventRecordID>70015</EventRecordID>
      <Channel>Application</Channel>
      <Computer>DEBERLEMBURGNG.net.plm.eds.com</Computer>
      <Security/>
    </System>
    <EventData>
      <Data>devenv.exe</Data>
      <Data>12.0.31101.0</Data>
      <Data>54548724</Data>
      <Data>KERNELBASE.dll</Data>
      <Data>6.1.7601.18409</Data>
      <Data>53159a86</Data>
      <Data>e0434352</Data>
      <Data>0000c42d</Data>
      <Data>3100</Data>
      <Data>01d06b08cb252558</Data>
      <Data>C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe</Data>
      <Data>C:\windows\syswow64\KERNELBASE.dll</Data>
      <Data>c83a9ef4-d6fc-11e4-92cc-bc305bec1593</Data>
    </EventData>
    <RenderingInfo Culture="de-DE">
      <Message>Faulting application name: devenv.exe, version: 12.0.31101.0, time stamp: 0x54548724
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x3100
Faulting application start time: 0x01d06b08cb252558
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
Faulting module path: C:\windows\syswow64\KERNELBASE.dll
Report Id: c83a9ef4-d6fc-11e4-92cc-bc305bec1593</Message>
      <Level>Error</Level>
      <Task>Application Crashing Events</Task>
      <Opcode>Info</Opcode>
      <Channel/>
      <Provider/>
      <Keywords>
        <Keyword>Classic</Keyword>
      </Keywords>
    </RenderingInfo>
  </Event>
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
      <Provider Name=".NET Runtime"/>
      <EventID Qualifiers="0">1026</EventID>
      <Level>2</Level>
      <Task>0</Task>
      <Keywords>0x80000000000000</Keywords>
      <TimeCreated SystemTime="2015-03-30T16:49:50.000000000Z"/>
      <EventRecordID>70014</EventRecordID>
      <Channel>Application</Channel>
      <Computer>DEBERLEMBURGNG.net.plm.eds.com</Computer>
      <Security/>
    </System>
    <EventData>
      <Data>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
</Data>
    </EventData>
    <RenderingInfo Culture="de-DE">
      <Message>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
</Message>
      <Level>Error</Level>
      <Task/>
      <Opcode>Info</Opcode>
      <Channel/>
      <Provider/>
      <Keywords>
        <Keyword>Classic</Keyword>
      </Keywords>
    </RenderingInfo>
  </Event>
</Events>
```

After the crash I hit "debug" and got the following "extended" information:

    System.InvalidOperationException was unhandled
    Message: An unhandled exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll
    Additional information: '[Unknown]' property does not point to a DependencyObject in path '(0).(1)[0].(2)'.

**Comment by nagits** [comment]
Thanks!
